### ISSUE TITLE
When is the hexo@4.2.0 supported？

### ISSUE THREAD

**Issue by wongqingbin** [JLHwung/hexo-offline#127]
hexo-site@0.0.0 /Users/wangqingbin/blog
├── UNMET PEER DEPENDENCY hexo@4.2.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-search@2.4.0
├── hexo-generator-tag@1.0.0
├── hexo-offline@1.0.0
├── hexo-related-popular-posts@4.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-wordcount@6.0.1

npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0

**Comment by JLHwung** [comment]
Can yon confirm that `hexo-offline` works with `hexo@4`? If so I can broaden the peer deps to `^3.2.2 || ^4.0.0`.

**Comment by karuboniru** [comment]
> Can yon confirm that `hexo-offline` works with `hexo@4`? If so I can broaden the peer deps to `^3.2.2 || ^4.0.0`.

It works here, with `hexo@4`.
