### ISSUE TITLE
How to update my hexo site ?

### ISSUE THREAD

**Issue by TongchengQiu** [JLHwung/hexo-offline#38]
When I want to update my site as run `hexo clean && hexo d`, but the offline resource is long cache so that my site will not update. Only unregister my service workers I can update.

**Comment by JLHwung** [comment]
The default policy of `sw-precache` is cache-first, so the cache will get updated and the next time you go to the site, the updated content will be fetched from the cache. See https://github.com/vuejs-templates/pwa/issues/70#issuecomment-333220353
